---
title: "SMEs Fintech&Sustainability in Triveneto Area"
subtitle: "Model and Hypotesis testing"
author: "Elisa Nardini"
date: "2024-02-02"
output: pdf_document
---

## Dataset and package reading

```{r setup, include=FALSE}
rm(list = ls())

# Set Wd ------------------------------------------------------------------------
setwd("~/Desktop/R/fintechsustainabilty")
df <- read.csv("dataset_en.csv")

# Packages ----------------------------------------------------------------------
library(ggplot2)
library(plotly)
library(tidyverse)
library(car)
library(corrplot)
library(caret)

# Import Data -------------------------------------------------------------------
dataset <- read.csv("dataset_en.csv")
dataset <- dataset[, -c(1)]

```

```{r}
############################################################ Valutazione affermazioni su benefici Scala 1-7 ###############################################   

# H1 FINTECH ADOPTION -> COMPETITIVNESS [Economical Sustainability Performance(ECP), Social Sustainability Performance, Access to Finance (AF)]
# H2 FINTECH ADOPTION -> Business Performance 
# H3 FINTECH ADOPTION -> Environmental Performance(ENP)
# H4 Competitività -> Performance

# X6 - Horizontals                                                    ###Fintech Adoption
# X7 - Vertials                                                       ###Fintech Adoption 

# X15 - Utilizzo strumenti Fintech per sostenibilità (Si/No)          ###Fintech Adoption
# X16 - Quanti progetti in atto                                       ###Fintech Adoption


# X19 - CO2                                                         ###Environmental Performance(ENP)
# X20 - Risparmio Energetico                                        ###Environmental Performance(ENP)
# X21 - Riduzione rifiuti                                           ###Environmental Performance(ENP)
# X22 - Riutilizzo materiali di scarto                              ###Environmental Performance(ENP)


# X23 - Ottimizzazione risorse                                      ###Economical Sustainability Performance(ECP)        ###Competitività
# X24 - Risparmio costi per la sostenibilità                        ###Economical Sustainability Performance(ECP)        ###Competitività

# X25 - Adeguamento normativo                                       ###Social Sustainability Performance                 ###Competitività
# X26 - Soddisfazione dei clienti                                   ###Social Sustainability Performance                 ###Competitività
# X27 - Miglioramento della reportistica                            ###Social Sustainability Performance                 ###Competitività

# X28 - Accesso al mercato dei capitali                             ###Access to Finance (AF)                            ###Competitività


# X29 - Redditività sostenibile                                     ###Business Performance
# X30 - Produttività                                                ###Business Performance
# X31 - Crescita                                                    ###Business Performance
# X32 - Redditività delle operazioni                                ###Business Performance
```

```{r}
# New class variable CLASS_ESPERIENZA  -----------------------------------------------------

dataset$CLASS_ESPERIENZA <- cut(dataset$X1,
                                    breaks = c(-Inf, 2, 10, Inf),
                                    labels = c("<2", "2-10", ">10"))


dataset$CLASS_ESPERIENZA <- factor(dataset$CLASS_ESPERIENZA, levels = c("<2", "2-10", ">10"))

```

```{r}
names(dataset)[names(dataset) == "X2"] <- "AREA"
names(dataset)[names(dataset) == "X3"] <- "SETTORE"
names(dataset)[names(dataset) == "X5"] <- "FAM_FINTECH"
names(dataset)[names(dataset) == "X15"] <- "FINTECH_PROJ"
names(dataset)[names(dataset) == "X16"] <- "NUM_FINTECH_PROJ"
names(dataset)[names(dataset) == "X33"] <- "PROBLEMS"


dataset$PROBLEMS <- ifelse(is.na(dataset$PROBLEMS), "not specified", dataset$PROBLEMS)

dataset <- dataset[, -c(1, 4, 17, 18)]

```

```{r}
dataset <- na.omit(dataset)
```

```{r}

# VERTICALS DUMMY

dataset$Crowfunding <- ifelse(dataset$X9 == "Si", 1, 0)
dataset$P2P <- ifelse(dataset$X10 == "Si", 1, 0)
dataset$MobilePay <- ifelse(dataset$X11 == "Si", 1, 0)
dataset$NFT <- ifelse(dataset$X12 == "Si", 1, 0)

```

```{r}

# HORIZONTALS DUMMY 

dataset$Blockchain <- ifelse(dataset$X6 == "Si", 1, 0)
dataset$AI <- ifelse(dataset$X7 == "Si", 1, 0)
dataset$ML <- ifelse(dataset$X8 == "Si", 1, 0)
dataset$Chatbot <- ifelse(dataset$X13 == "Si", 1, 0)
dataset$RPA <- ifelse(dataset$X14 == "Si", 1, 0)

```

```{r}

# FINTECH_PROJ  DUMMY 

dataset$FINTECH_PROJ <- ifelse(dataset$FINTECH_PROJ == "Si", 1, 0)

```


```{r}
dataset <- dataset[, -c(4, 5, 6, 7, 8, 9, 10, 11, 12)]
```


```{r}

# CONTROL VARIABLES DUMMYS

dummy_trans <- dummyVars(~ AREA + SETTORE + CLASS_ESPERIENZA, data = dataset)
dummy_variables <- predict(dummy_trans, newdata = dataset)
dataset <- cbind(dataset, dummy_variables)

```

```{r}
dataset <- dataset[, -c(1, 2, 20, 21)]
```

```{r}

# BOOTSTRAPING

# Converti le variabili dummy in factor
colonne_da_trattare <- 18:42  # Specifica le colonne da trattare

for (colonna in colonne_da_trattare) 
  dataset[[colonna]] <- factor(dataset[[colonna]], levels = c(0, 1))


dataset$FINTECH_PROJ <- factor(dataset$FINTECH_PROJ, levels = c(0, 1))




# Funzione per il bootstrapping
bootstrapped_data <- function(data) {
  n <- nrow(data)
  sampled_indices <- sample(1:n, replace = TRUE, size = n)
  return(data[sampled_indices, ])
}

# Genera 1000 campioni di dati sintetici utilizzando il bootstrapping
num_bootstraps <- 100
bootstrapped_datasets <- lapply(1:num_bootstraps, function(x) bootstrapped_data(dataset))

# Visualizza i primi dati sintetici generati
head(bootstrapped_datasets[[1]])
```

```{r}
# Unisci i campioni di dati sintetici al dataset originale
extended_dataset <- do.call(rbind, c(list(dataset), bootstrapped_datasets))

# Visualizza i primi dati sintetici generati
head(extended_dataset)
```


```{r}

#   ***********************ONLY FINTECH PROJECT*****************************
  
  
# Prendo in considerazione solamente i valori Si circa l'utilizzo di strumenti fintech per la sostenibilità 
extended_dataset <- extended_dataset[extended_dataset$FINTECH_PROJ == 1 , ]
```


```{r}
# Ipostesi 1 : COMPETITIVITA'
extended_dataset$COMP <- rowMeans(extended_dataset[, c("X23", "X24", "X25", "X26", "X27")], na.rm = TRUE)

# dataset$ECP <- rowMeans(dataset[, c("X23", "X24")])
# dataset$SSP <- rowMeans(dataset[, c("X25", "X26", "X27")])
# Access to Finance (AF)  


# Ipostesi 2 : PERFORMANCE
extended_dataset$PERFORMANCE <- rowMeans(extended_dataset[, c("X29", "X30", "X31", "X32")], na.rm = TRUE)


# Ipotesi 3 : ENVIRONMENTAL PERFORMANCE
extended_dataset$ENP <- rowMeans(extended_dataset[, c("X25", "X20", "X21", "X22")])
```


```{r}
############################################## REGRESSIONE ##########################################

# DA RUNNARE COME PRIMO STEP MA NON INSERIRE COME RISULTATO


dati_regressione <- extended_dataset[, c("COMP", "NUM_FINTECH_PROJ", "FAM_FINTECH", "Crowfunding", "P2P", "MobilePay", "NFT", "Blockchain", "AI", "ML", "Chatbot", "RPA")]

#dati_regressione[is.na(dati_regressione)] <- 1
#modello_regressione <- lm(X19 ~ ., data = dati_regressione)

modello_regressione <- lm(COMP ~ ., data = dati_regressione, na.action = na.exclude)
modello_backward <- step(modello_regressione, direction = "backward")
summary(modello_backward)

# summary(modello_regressione)
vif_values <- vif(modello_backward)
print(vif_values)

```
 y = b0 + b1x1 + 0.66*32 + b3x3



```{r}
#dati_regressione <- extended_dataset[, c("ENP", "NUM_FINTECH_PROJ", "FAM_FINTECH", "Crowfunding", "P2P", "MobilePay", "NFT", "Blockchain", "AI", "ML", "Chatbot", "RPA", "AREAhuman resources ", "AREAfinancial and administrative department ", "AREAmanagement and ownership ", "AREAoperational area ", "SETTOREagriculture, forestry and fishing ", "SETTOREconstructions ", "SETTOREfinancial and insurance activities ", "SETTOREinformation and communication services ", "SETTOREmanufacturing and industrial activities ", "SETTOREproduction of intermediate goods, energy and waste ", "SETTOREsocial services ", "SETTOREtrade, transport and warehousing ", "CLASS_ESPERIENZA.2-10", "CLASS_ESPERIENZA.>10", "CLASS_ESPERIENZA.<2")]

```

```{r}
############################################## REGRESSIONE CON CONTROL VARIABLES ##########################################


# AREA
# SETTORE 
# CLASS_ESPERIENZA

# Sostituisci COMP,PERFORMANCE,ENP
dati_regressione <- extended_dataset[, c("COMP", "NUM_FINTECH_PROJ", "FAM_FINTECH", "Crowfunding", "P2P", "MobilePay", "NFT", "Blockchain", "AI", "ML", "Chatbot", "RPA", "AREAhuman resources ", "AREAfinancial and administrative department ", "AREAmanagement and ownership ", "AREAoperational area ", "SETTOREagriculture, forestry and fishing ", "SETTOREconstructions ", "SETTOREfinancial and insurance activities ", "SETTOREinformation and communication services ", "SETTOREmanufacturing and industrial activities ", "SETTOREproduction of intermediate goods, energy and waste ", "SETTOREsocial services ", "SETTOREtrade, transport and warehousing ", "CLASS_ESPERIENZA.2-10", "CLASS_ESPERIENZA.>10", "CLASS_ESPERIENZA.<2")]
                                     

# Sostituisci COMP,PERFORMANCE,ENP
modello_regressione <- lm(COMP ~ ., data = dati_regressione, na.action = na.exclude)
modello_backward <- step(modello_regressione, direction = "backward")
summary(modello_backward)

#summary(modello_regressione)
vif_values <- vif(modello_backward)
print(vif_values)
```

